use std::fs;
use std::path::Path;

use anyhow::{anyhow, bail, Context};
use include_dir::{include_dir, Dir};

use crate::state::write_text;
use crate::DynResult;

static SKILLS_DIR: Dir<'_> = include_dir!("$CARGO_MANIFEST_DIR/skills");

const AGENTS_HEADER: &str = "# AI Agent Skills

This project ships skills for AI coding assistants. They are regenerated by\n\
`logos-scaffold new` and `logos-scaffold init`; commit them so your team gets\n\
the same guidance.

- **Claude Code** reads `.claude/skills/<name>/SKILL.md` directly.
- **Cursor** reads `.cursor/rules/<name>.mdc`.
- **Codex / other agents** can open the matching skill below when its trigger applies.

| Skill | When it applies |
|---|---|
";

const AGENTS_FOOTER: &str = "\nOpen the matching skill file when its activation criteria apply.\n";

/// Materialize the canonical scaffold AI skills into `target`:
///
/// - `<target>/.claude/skills/<name>/SKILL.md` — verbatim canonical source
///   (Claude Code's native skill format).
/// - `<target>/.cursor/rules/<name>.mdc` — Cursor Project Rule with frontmatter
///   rewritten (`name:` dropped; `alwaysApply: false` added).
/// - `<target>/AGENTS.md` — pointer file at the project root listing every
///   skill with its description (Codex / cross-tool convention).
///
/// Idempotent: re-running overwrites each shipped skill file with its current
/// canonical content. Skills the user has added under `.claude/skills/<other>/`
/// or `.cursor/rules/<other>.mdc` are not touched.
pub(crate) fn apply_skills(target: &Path) -> DynResult<()> {
    let mut entries: Vec<(String, String)> = Vec::new();

    for skill_dir in SKILLS_DIR.dirs() {
        let name = skill_dir
            .path()
            .file_name()
            .ok_or_else(|| anyhow!("invalid skill dir path: {}", skill_dir.path().display()))?
            .to_string_lossy()
            .into_owned();

        let skill_md = skill_dir
            .files()
            .find(|f| f.path().file_name() == Some(std::ffi::OsStr::new("SKILL.md")))
            .ok_or_else(|| anyhow!("skill `{name}` is missing SKILL.md"))?;

        let raw = skill_md
            .contents_utf8()
            .ok_or_else(|| anyhow!("SKILL.md for skill `{name}` is not valid UTF-8"))?;

        let parsed = parse_skill_frontmatter(raw)
            .with_context(|| format!("parsing frontmatter for skill `{name}`"))?;

        let claude_path = target
            .join(".claude")
            .join("skills")
            .join(&name)
            .join("SKILL.md");
        if let Some(parent) = claude_path.parent() {
            fs::create_dir_all(parent)?;
        }
        write_text(&claude_path, raw)?;

        let mdc = render_cursor_mdc(&parsed.description, &parsed.body);
        let cursor_path = target
            .join(".cursor")
            .join("rules")
            .join(format!("{name}.mdc"));
        if let Some(parent) = cursor_path.parent() {
            fs::create_dir_all(parent)?;
        }
        write_text(&cursor_path, &mdc)?;

        entries.push((name, parsed.description));
    }

    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut agents = String::from(AGENTS_HEADER);
    for (name, description) in &entries {
        agents.push_str(&format!(
            "| [`{name}`](.claude/skills/{name}/SKILL.md) | {description} |\n"
        ));
    }
    agents.push_str(AGENTS_FOOTER);
    write_text(&target.join("AGENTS.md"), &agents)?;

    Ok(())
}

#[derive(Debug)]
struct ParsedSkill {
    description: String,
    body: String,
}

fn parse_skill_frontmatter(raw: &str) -> DynResult<ParsedSkill> {
    let trimmed = raw.trim_start_matches('\u{feff}');
    let after_open = trimmed
        .strip_prefix("---\n")
        .or_else(|| trimmed.strip_prefix("---\r\n"))
        .ok_or_else(|| anyhow!("SKILL.md missing leading `---` frontmatter delimiter"))?;

    let (frontmatter, body) = split_frontmatter(after_open)
        .ok_or_else(|| anyhow!("SKILL.md missing closing `---` for frontmatter"))?;

    let mut description: Option<String> = None;
    let mut buf = String::new();
    let mut in_description = false;
    for line in frontmatter.lines() {
        if let Some(rest) = line.strip_prefix("description:") {
            if description.is_some() {
                bail!("SKILL.md frontmatter has multiple `description:` lines");
            }
            buf = rest.trim().to_string();
            in_description = true;
        } else if in_description && (line.starts_with(' ') || line.starts_with('\t')) {
            if !buf.is_empty() {
                buf.push(' ');
            }
            buf.push_str(line.trim());
        } else {
            if in_description {
                description = Some(std::mem::take(&mut buf));
                in_description = false;
            }
        }
    }
    if in_description {
        description = Some(buf);
    }

    let description =
        description.ok_or_else(|| anyhow!("SKILL.md frontmatter missing `description:` field"))?;
    if description.is_empty() {
        bail!("SKILL.md frontmatter has empty `description:`");
    }

    Ok(ParsedSkill {
        description,
        body: body.to_string(),
    })
}

fn split_frontmatter(after_open: &str) -> Option<(&str, &str)> {
    let mut offset = 0;
    for line in after_open.split_inclusive('\n') {
        let line_without_lf = line.strip_suffix('\n').unwrap_or(line);
        let line_text = line_without_lf
            .strip_suffix('\r')
            .unwrap_or(line_without_lf);
        if line_text == "---" {
            return Some((&after_open[..offset], &after_open[offset + line.len()..]));
        }
        offset += line.len();
    }

    None
}

fn render_cursor_mdc(description: &str, body: &str) -> String {
    format!("---\ndescription: {description}\nalwaysApply: false\n---\n{body}")
}

#[cfg(test)]
mod tests {
    use std::fs;

    use super::{apply_skills, parse_skill_frontmatter, render_cursor_mdc, SKILLS_DIR};
    use tempfile::{tempdir, TempDir};

    fn mk_temp_dir() -> TempDir {
        tempdir().expect("failed to create temporary test directory")
    }

    fn shipped_skill_names() -> Vec<String> {
        let mut names: Vec<String> = SKILLS_DIR
            .dirs()
            .map(|d| {
                d.path()
                    .file_name()
                    .unwrap_or_default()
                    .to_string_lossy()
                    .to_string()
            })
            .filter(|s| !s.is_empty())
            .collect();
        names.sort();
        names
    }

    #[test]
    fn ships_the_expected_four_skills() {
        let names = shipped_skill_names();
        assert_eq!(
            names,
            vec![
                "basecamp".to_string(),
                "lez-framework-template".to_string(),
                "lez-template".to_string(),
                "lgs-cli".to_string(),
            ],
            "shipped skills set drifted; update the test if intentional"
        );
    }

    #[test]
    fn apply_skills_writes_claude_cursor_and_agents_layouts() {
        let temp = mk_temp_dir();
        let target = temp.path();
        apply_skills(target).expect("apply_skills");

        for name in shipped_skill_names() {
            let claude = target.join(format!(".claude/skills/{name}/SKILL.md"));
            assert!(
                claude.exists(),
                "missing claude skill: {}",
                claude.display()
            );

            let cursor = target.join(format!(".cursor/rules/{name}.mdc"));
            assert!(cursor.exists(), "missing cursor rule: {}", cursor.display());
        }

        let agents = target.join("AGENTS.md");
        assert!(agents.exists(), "AGENTS.md should be at project root");
        let agents_text = fs::read_to_string(&agents).expect("read AGENTS.md");
        for name in shipped_skill_names() {
            assert!(
                agents_text.contains(&format!("[`{name}`]")),
                "AGENTS.md is missing skill `{name}`; got:\n{agents_text}"
            );
        }
    }

    #[test]
    fn claude_skill_md_is_byte_identical_to_source() {
        let temp = mk_temp_dir();
        let target = temp.path();
        apply_skills(target).expect("apply_skills");

        let written = fs::read_to_string(target.join(".claude/skills/lgs-cli/SKILL.md"))
            .expect("read written SKILL.md");
        let source = include_str!("../../skills/lgs-cli/SKILL.md");
        assert_eq!(
            written, source,
            ".claude/skills/<name>/SKILL.md must be byte-identical to the canonical source"
        );
    }

    #[test]
    fn cursor_mdc_drops_name_field_and_adds_always_apply() {
        let temp = mk_temp_dir();
        let target = temp.path();
        apply_skills(target).expect("apply_skills");

        let mdc =
            fs::read_to_string(target.join(".cursor/rules/lgs-cli.mdc")).expect("read lgs-cli.mdc");
        // First line opens frontmatter; we expect description + alwaysApply
        // before the closing delimiter, with no `name:` field.
        let (frontmatter, _body) = mdc
            .strip_prefix("---\n")
            .and_then(|rest| rest.split_once("\n---\n"))
            .expect("mdc has well-formed frontmatter");
        assert!(
            frontmatter.starts_with("description:"),
            "mdc frontmatter must lead with description; got:\n{frontmatter}"
        );
        assert!(
            frontmatter.contains("alwaysApply: false"),
            "mdc frontmatter must include alwaysApply: false; got:\n{frontmatter}"
        );
        assert!(
            !frontmatter.contains("name:"),
            "mdc frontmatter must not include the source `name:` field; got:\n{frontmatter}"
        );
    }

    #[test]
    fn apply_skills_is_idempotent() {
        let temp = mk_temp_dir();
        let target = temp.path();
        apply_skills(target).expect("first apply");
        let claude_first = fs::read_to_string(target.join(".claude/skills/lgs-cli/SKILL.md"))
            .expect("read claude after first");
        let mdc_first = fs::read_to_string(target.join(".cursor/rules/lgs-cli.mdc"))
            .expect("read mdc after first");
        let agents_first = fs::read_to_string(target.join("AGENTS.md")).expect("read agents first");

        apply_skills(target).expect("second apply");
        let claude_second = fs::read_to_string(target.join(".claude/skills/lgs-cli/SKILL.md"))
            .expect("read claude after second");
        let mdc_second = fs::read_to_string(target.join(".cursor/rules/lgs-cli.mdc"))
            .expect("read mdc after second");
        let agents_second =
            fs::read_to_string(target.join("AGENTS.md")).expect("read agents second");

        assert_eq!(claude_first, claude_second);
        assert_eq!(mdc_first, mdc_second);
        assert_eq!(agents_first, agents_second);
    }

    #[test]
    fn apply_skills_preserves_user_added_skill_files() {
        let temp = mk_temp_dir();
        let target = temp.path();
        let custom_claude = target.join(".claude/skills/team-custom/SKILL.md");
        let custom_cursor = target.join(".cursor/rules/team-custom.mdc");
        fs::create_dir_all(custom_claude.parent().unwrap()).expect("mkdir claude");
        fs::create_dir_all(custom_cursor.parent().unwrap()).expect("mkdir cursor");
        fs::write(&custom_claude, "team-only canonical").expect("write team claude skill");
        fs::write(&custom_cursor, "team-only cursor rule").expect("write team cursor rule");

        apply_skills(target).expect("apply_skills");

        assert_eq!(
            fs::read_to_string(&custom_claude).expect("read custom claude"),
            "team-only canonical"
        );
        assert_eq!(
            fs::read_to_string(&custom_cursor).expect("read custom cursor"),
            "team-only cursor rule"
        );
    }

    #[test]
    fn parse_skill_frontmatter_extracts_description_and_body() {
        let raw = "---\nname: foo\ndescription: hello world\n---\n# Body\n\ntext\n";
        let parsed = parse_skill_frontmatter(raw).expect("parse");
        assert_eq!(parsed.description, "hello world");
        assert_eq!(parsed.body, "# Body\n\ntext\n");
    }

    #[test]
    fn parse_skill_frontmatter_handles_multiline_description() {
        let raw = "---\nname: foo\ndescription: first\n  continued line\nother: x\n---\nbody\n";
        let parsed = parse_skill_frontmatter(raw).expect("parse");
        assert_eq!(parsed.description, "first continued line");
    }

    #[test]
    fn parse_skill_frontmatter_rejects_missing_delimiter() {
        let raw = "name: foo\ndescription: bar\n";
        let err = parse_skill_frontmatter(raw).expect_err("should reject");
        assert!(
            err.to_string().contains("missing leading"),
            "unexpected error: {err}"
        );
    }

    #[test]
    fn parse_skill_frontmatter_rejects_non_delimiter_close_line() {
        let raw = "---\nname: foo\ndescription: bar\n---foo\n# Body\n";
        let err = parse_skill_frontmatter(raw).expect_err("should reject");
        assert!(
            err.to_string().contains("missing closing"),
            "unexpected error: {err}"
        );
    }

    #[test]
    fn parse_skill_frontmatter_rejects_missing_description() {
        let raw = "---\nname: foo\n---\nbody\n";
        let err = parse_skill_frontmatter(raw).expect_err("should reject");
        assert!(
            err.to_string().contains("missing `description:`"),
            "unexpected error: {err}"
        );
    }

    #[test]
    fn render_cursor_mdc_preserves_body_verbatim() {
        let mdc = render_cursor_mdc("desc text", "# Body\n\nLine.\n");
        assert_eq!(
            mdc,
            "---\ndescription: desc text\nalwaysApply: false\n---\n# Body\n\nLine.\n"
        );
    }
}
